### ISSUE TITLE
Port 51001 excludes ports from Gemini Hub

### ISSUE THREAD

**Issue by jmw182** [zeeMonkeez/CerebusWireshark#2]
Hi,

I tried using the Cerebus400.lua plugin to sniff packets from a new Gemini Hub (connected directly to the PC without an NSP). This didn't work at first but I figured out it was because the Gemini Hub uses a different port than the NSPs (51002 vs 51001).

From cbhwlib.h version 4.0:
```C
#define cbNET_UDP_ADDR_INST         "192.168.137.1"   // Cerebus default address
#define cbNET_UDP_ADDR_CNT          "192.168.137.128" // Gemini NSP default control address
#define cbNET_UDP_ADDR_BCAST        "192.168.137.255" // NSP default broadcast address
#define cbNET_UDP_PORT_BCAST        51002             // Neuroflow Data Port
#define cbNET_UDP_PORT_CNT          51001             // Neuroflow Control Port
// maximum udp datagram size used to transport cerebus packets, taken from MTU size
//#define cbCER_UDP_SIZE_MAX          1452 // Note that multiple packets may reside in one udp datagram as aggregate

#define cbNET_TCP_PORT_GEMINI       51005             // Neuroflow Data Port
#define cbNET_TCP_ADDR_GEMINI_HUB   "192.168.137.200" // NSP default control address

#define cbNET_UDP_ADDR_HOST         "192.168.137.199"   // Cerebus (central) default address
#define cbNET_UDP_ADDR_GEMINI_NSP   "192.168.137.128" // NSP default control address
#define cbNET_UDP_ADDR_GEMINI_HUB   "192.168.137.200" // HUB default control address
#define cbNET_UDP_ADDR_GEMINI_HUB2  "192.168.137.201" // HUB default control address
#define cbNET_UDP_ADDR_BCAST        "192.168.137.255" // NSP default broadcast address
#define cbNET_UDP_PORT_GEMINI_NSP   51001             // Gemini NSP Port
#define cbNET_UDP_PORT_GEMINI_HUB   51002             // Gemini HUB Port
#define cbNET_UDP_PORT_GEMINI_HUB2  51003             // Gemini HUB Port
//#define cbCER_UDP_SIZE_MAX          50000             // Note that multiple packets may reside in one udp datagram as aggregate
#define cbCER_UDP_SIZE_MAX          58080             // Note that multiple packets may reside in one udp datagram as aggregate

#define PROTOCOL_UDP        0
#define PROTOCOL_TCP        1
```

For my purposes I edited line 1387 (the ProtoMaker port definition) to change the port to 51002:
```lua
local ProtoMaker = klass:new{
    name='Cerebus',
    desc="Cerebus NSP Communication",
    colname="Cerebus",
    port=51002 -- 51001
}
```

Would it be feasible to update the plugin to support sniffing all relevant ports listed in cbhwlib.h (UDP 51001-51003, TCP 51005)? I am not familiar with lua so I do not feel confident making these changes myself.

Thanks,
Jeff Weiss
University of Pittsburgh

**Comment by cboulay** [comment]
Hi Jeff,

I'm sorry I didn't see this sooner. I somehow wasn't receiving notifications from this repo.

When I've been using this with Gemini, I've been making the same change as you.

I struggle with Lua. I'll ask around to see if I can find someone who can take care of this.

**Comment by jmw182** [comment]
@cboulay no problem for the delay, thanks for responding.

No urgency at all on this change, even just editing the readme or adding a new version like "Cerebus400gemini.lua" would be helpful for anyone else trying to figure this out.

**Comment by cboulay** [comment]
Please let us know if the latest version doesn't work for you.

**Comment by jmw182** [comment]
Thanks @cboulay, you're fast! I was also working on this in a fork at the same time 😄 

The updated master version works, but my alternate version will label Gemini packets as "Gemini" instead of "Cerebus," since, my approach was to make a second instance of the ProtoMaker class for the Gemini port.

https://github.com/jmw182/CerebusWireshark

**Comment by cboulay** [comment]
I'm not fast. Craig is (@cwatson-blackrock ).

The Cerebus / Gemini designation is maybe not the right model. 51001 is for "NSP". This includes the legacy NSP as well as the new NSP box that's part of the Gemini family. 51002 and 51003 are for "Hubs", which are exclusive to the Gemini family.
